from pathlib import Path
from typing import Annotated

import typer
from rich import print as rprint
from typer import Typer

from ._graph import from_json, from_release

kconfig_app = Typer()


@kconfig_app.command()
def build_graph(
    ctx: typer.Context,
    json_file: Annotated[
        Path | None, typer.Argument(help="Path to JSON file containing permission check request")
    ] = None,
    release_name: Annotated[str | None, typer.Option(help="Zephyr release name to fetch kconfig.json from")] = None,
) -> None:
    """Build graph from kconfig.json files generated by Zephyr Documentation System."""

    # either one of json_file or release_name must be provided
    if not json_file and not release_name:
        rprint("[red]Error: Either --json-file or --release-name must be provided.[/red]")
        raise typer.Exit(code=1)

    if json_file and release_name:
        rprint("[red]Error: Only one of --json-file or --release-name can be provided.[/red]")
        raise typer.Exit(code=1)

    if json_file:
        kconfig_doc = from_json(json_file)
    else:
        assert release_name is not None  # for type checker
        kconfig_doc = from_release(release_name)

    rprint(f"[green]Successfully built graph with {len(kconfig_doc.symbols)} items.[/green]")

    rprint(kconfig_doc.gh_base_url)
    rprint(kconfig_doc.zephyr_version)
