from pathlib import Path
from typing import Annotated, Any, cast

import typer
from rich import print as rprint
from rich.console import Console, Group
from rich.panel import Panel
from rich.table import Table
from typer import Typer

from zephyr_rtos_ai._types import CmdState

from ._graph import from_json, from_release
from ._models import KConfigDocItem
from ._types import KConfigCmdState

kconfig_app = Typer()


@kconfig_app.callback()
def process(
    ctx: typer.Context,
    json_file: Annotated[
        Path | None, typer.Argument(help="Path to JSON file containing permission check request")
    ] = None,
    release_name: Annotated[str | None, typer.Option(help="Zephyr release name to fetch kconfig.json from")] = None,
) -> None:
    """Build graph from kconfig.json files generated by Zephyr Documentation System."""

    state = cast(CmdState, ctx.obj)

    # either one of json_file or release_name must be provided
    if not json_file and not release_name:
        rprint("[red]Error: Either --json-file or --release-name must be provided.[/red]")
        raise typer.Exit(code=1)

    if json_file and release_name:
        rprint("[red]Error: Only one of --json-file or --release-name can be provided.[/red]")
        raise typer.Exit(code=1)

    if json_file:
        kconfig_doc = from_json(json_file)
    else:
        assert release_name is not None  # for type checker
        kconfig_doc = from_release(release_name)

    state.kconfig = KConfigCmdState()
    state.kconfig.doc = kconfig_doc


@kconfig_app.command()
def describe(
    ctx: typer.Context,
    name: Annotated[str, typer.Argument(help="The CONFIG_ to describe")],
) -> None:
    """Describe the CONFIG_ symbol"""

    state = cast(CmdState, ctx.obj)

    config_items = state.kconfig.doc.get_symbols(name)

    if not config_items:
        rprint(f"[red]Error: Symbol {name} not found in KConfig document.[/red]")
        return

    console = Console()

    def _make_table(column_name: str, items: list[str]) -> Table:
        """Make a simple table with items."""
        table = Table(show_header=True, header_style="bold magenta")
        table.add_column(column_name, style="white")
        for item in items:
            table.add_row(item)
        return table

    def _display_config_item(console: Console, config_item: KConfigDocItem) -> None:
        """Display a single KConfig item with its properties."""

        # Create main info table
        info_table = Table(show_header=False, box=None, padding=(0, 1))
        info_table.add_column("Property", style="cyan", no_wrap=True)
        info_table.add_column("Value", style="white")

        if config_item.prompt:
            info_table.add_row("Prompt", config_item.prompt)
        info_table.add_row("Type", config_item.type or "N/A")
        info_table.add_row("Dependencies", config_item.dependencies)

        defaults_table = _make_table("Defaults", config_item.defaults) if config_item.defaults else None
        selects_table = _make_table("Selects", config_item.selects) if config_item.selects else None
        implies_table = _make_table("Implies", config_item.implies) if config_item.implies else None
        selected_by_table = _make_table("Selected By", config_item.selected_by) if config_item.selected_by else None
        implied_by_table = _make_table("Implied By", config_item.implied_by) if config_item.implied_by else None
        choices_table = _make_table("Choices", config_item.choices) if config_item.choices else None

        items: list[Any] = []
        if config_item.help:
            items.append(
                Panel(
                    config_item.help,
                    title="Description",
                    border_style="blue",
                )
            )
        if defaults_table:
            items.append(defaults_table)
        if selects_table:
            items.append(selects_table)
        if implies_table:
            items.append(implies_table)
        if selected_by_table:
            items.append(selected_by_table)
        if implied_by_table:
            items.append(implied_by_table)
        if choices_table:
            items.append(choices_table)

        panel_group = Group(info_table, *items)

        console.print(Panel(panel_group, title=f"{config_item.name}", border_style="green"), markup=False)

    for item in config_items:
        _display_config_item(console, item)
